// 01_rollup/vue/App.vue
<template>
  <div>
    <div>{{ counter }}</div>
    <button @click="counter++">+1</button>
    <button @click="counter--">+1</button>
    <button @click="counter -= 2">-2</button>
  </div>
</template>

<script setup>
import { ref } from "vue";
const counter = ref(0);
</script>

<style scoped></style>

// 02_vite/src/views/App.jsx
import React, { useState } from "react";
const App = function () {
  const [counter, setCounter] = useState(0);
  return (
    <div className="app">
      <h2>react: {counter}</h2>
      <button onClick={(e) => setCounter(counter + 1)}>+1</button>
      <button onClick={(e) => setCounter(counter - 1)}>-1</button>
    </div>
  );
}

export default App
